CREATE TABLE "USERS" (
    "ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    "USERNAME" VARCHAR(30) NOT NULL UNIQUE,
    "PASSWORD" CHAR(20) NOT NULL,
    "FIRST_NAME" VARCHAR(100) NOT NULL,
    "LAST_NAME" VARCHAR(100) NOT NULL,
    "DB_NAME" VARCHAR(30),
    "DB_USER" VARCHAR(30),
    "DB_PASSWORD" VARCHAR(30)
);